# Generated by Django 3.1.7 on 2021-03-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210323_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='winner',
            field=models.CharField(max_length=100),
        ),
    ]
