# Generated by Django 3.1.7 on 2021-03-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210323_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='watchers',
        ),
        migrations.AddField(
            model_name='item',
            name='watchers',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='winner',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
