# Generated by Django 3.1.7 on 2021-03-23 22:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20210323_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='watchers',
        ),
        migrations.AddField(
            model_name='item',
            name='watchers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
