# Generated by Django 3.2.2 on 2021-05-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20210323_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='name',
            field=models.CharField(choices=[('Vehicles', 'Vehicles'), ('Sport', 'Sport'), ('Electronics', 'Electronics'), ('Accessories', 'Accessories'), ('Other', 'Others')], max_length=25),
        ),
    ]
